---
# ----- BME280 Temperature/Pressure/Humidity Sensor -----

- name: copy scripts
  copy: >
    dest={{ working_dir }}
    src={{ item }}
    mode=0777
  with_items: "{{ script_files }}"
    
- name: make logging directory
  file: >
    path={{ logging_dir }}
    state=directory

- name: set cron
  cron: >
    name='check temperature'
    job='{{ working_dir }}/{{ script_files[0] }}'
    minute='*/1'
    backup=yes
    state=present
    disabled={{ bme280_disabled | default('no') }}
  notify:
    - restart cron
