---
# ----- distribute i2c sensor -----

- name: include i2c vars
  include_vars: "{{ item }}_vars.yml"
  with_items: "{{ i2c_modules }}"

- name: include i2c module
  include_tasks: "{{ module_item }}.yml"
  with_items: "{{ i2c_modules }}"
  # change loop variable of 'with_item' as module_item 
  loop_control:
    loop_var: module_item
