---
# ----- Using 1-Wire I2C Master -----
    
- name: make logging directory for OWFS
  file: >
    path={{ owfs_logging_dir }}
    state=directory
    recurse=yes

- name: copy scripts for OWFS
  copy: >
    dest={{ owfs_working_dir }}
    src={{ owfs_script_file }}
    mode=0777

- name: set cron for OWFS
  cron: >
    name='check temperature by using OWFS'
    job='{{ owfs_working_dir }}/{{ owfs_script_file }}'
    minute='*/1'
    backup=yes
    state=present
    disabled={{ owfs_disabled | default('no') }}
  notify:
    - restart cron
