---
# ----- Using 1-Wire I2C Master -----

- block:
  - name: make logging directory for OWFS
    file:
      path: "{{ owfs.logging_dir }}"
      state: directory
      recurse: true

  - name: copy scripts for OWFS
    copy:
      dest: "{{ owfs.working_dir }}"
      src:  "{{ owfs.script_file }}"
      mode: 0777

  - name: set cron for OWFS
    cron:
      name: 'check temperature by using OWFS'
      job:  "{{ owfs.working_dir }}/{{ owfs.script_file }}"
      minute: '*/1'
      backup: true
      state:  present
      disabled: "{{ not owfsQ.enabled | default('false') }}"
    notify:
      - restart cron
  when: owfsQ.installed