---
# ----- Set RTC module -----
#
# Need variable: rtc_type
#
#- debug: var=rtc_type
#- debug: var=rtc_param[rtc_type]
#- debug: var=rtc_param[rtc_type].name
#- debug: var=rtc_param[rtc_type].i2c_addr

- debug: msg="RTC is {{ rtcQ.rtc_type }}"
  when: rtc_param is defined

- name: copy service file for RTC
  become: yes
  template:
    src: rtc.service.j2
    dest: '/etc/systemd/system/rtc.service'
    owner: root
    group: root
    mode: 0644
  register: rtc_result
  when: rtc_param is defined

- name: set RTC as servie
  become: yes
  systemd:
    name: rtc
    state: restarted
    daemon_reload: yes
    enabled: true

- name: reboot machine
  include: roles/common/reboot.yml
  when: rtc_result|changed
