---
# ----- Set RTC module -----
#
# Need variable: rtc_type
#
#- debug: var=rtc_type
#- debug: var=rtc_param[rtc_type]
#- debug: var=rtc_param[rtc_type].name
#- debug: var=rtc_param[rtc_type].i2c_addr

- name: copy service file
  become: yes
  template: >
    src=rtc.service.j2
    dest=/etc/systemd/system/rtc.service
    owner=root
    group=root
    mode=0644
  register: rtc

- name: reboot machine
  include: roles/common/reboot.yml
  when: rtc|changed