---
- name: find Arduino IDE archive files
  shell: find *arduino* | grep tar.xz | sort -k 1,1n -k 2,2n -k 3,3n -t'.'
  args:
    executable: /bin/bash
    chdir: roles
  delegate_to: localhost
  register: result
  changed_when: no

- set_fact:
    arduino_file: "roles/{{ result.stdout_lines[-1] }}"

- debug: var=arduino_file

- name: Copy archive file
  become: true
  copy:
    src:  "{{ arduino_file }}"
    dest: "{{ src_dest }}"

- name: Unarchive
  become: true
  unarchive:
    src:  "{{ src_dest }}/{{ arduino_file | basename }}"
    dest: "{{ src_lib }}"
    copy: false
    list_files: true
  register: ide

- debug: var=ide.files[0]
      
- name: make links
  become: true
  file:
    src:   "{{ item.path }}"
    dest:  "{{ item.dest }}"
    state: link
  with_items:
    - { path: "{{ ide.files[0] }}", dest: "{{ src_lib }}/arduino" }
    - { path: "../lib/arduino/arduino", dest: "{{ src_bin }}/arduino" }
    
- name: install
  shell: sh install.sh
  args:
    chdir: "{{ src_lib }}/arduino/"

