---
- name: Build Scientific Python on Raspberry pi
  hosts: QuadCore
  environment:
    PATH: "{{ build_sp.setup_paths | join(':')}}"
  pre_tasks:
    - import_tasks: 'roles/common/get_board_kind.yml'
  roles:
    - apt_get_upgrade
    - install_pyenv
    - build_scientific-python
