---
- name: Check CPU Temperatures of Raspberry Pis
  hosts: all
  gather_facts: no
  tasks:
    - name: read cpu temperatures
      shell: vcgencmd measure_temp
      register: result
      changed_when: result.stderr != ""
    - debug: var=result.stdout