---
- name: check the model of Raspberry Pi
  hosts: all
  gather_facts: false
  tasks:  
    - shell: gpio -v | grep Type
      args:
        executable: /bin/bash
      register: pimodel
      ignore_errors: true
      changed_when: pimodel.stderr != ""
      
    - debug: var=pimodel.stdout
