---
- name: Install OWFS on Raspberry Pis
  hosts: owfs
  become: yes
  environment:
    LANG: C
    LC_ALL: C
    LC_MESSAGES: C
  roles:
    - apt_get_update
    - install_owfs 
    - { role: enable_modules, enable_i2c_state: enable }
    - { role: i2c_sensor, modules: [ owfs ] }