---
- name: Install OWFS on Raspberry Pis
  hosts: owfs
  become: yes
  environment:
    LANG: C
    LC_ALL: C
    LC_MESSAGES: C
  roles:
    - role: enable_modules
      enable_i2c_state: enable
    - apt_get_update
    - install_owfs
