---
- name: setup pyenv & pyenv-virtualenv
  hosts: Tinker.local
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_user_dir }}/.pyenv/plugins/pyenv-virtualenv/shims:{{ ansible_user_dir }}/.pyenv/shims:{{ ansible_user_dir }}/.pyenv/bin"
    
  tasks:
    - shell: echo $PATH
      register: result
      changed_when: no
      
    - debug: var=result
      