---
- name: Raspberry Pi's First Setup
  hosts: all
  pre_tasks:
    - include_tasks: 'roles/common/get_board_kind.yml'

  roles:
    # set SSH public key
    - set_authorized_key
    # setup timezone, keyboard, locale
    - international_setting
    # set Wi-Fi configure
    - setup_usb_wifi_adapter
    - { role: setup_wifi_ap, board: "{{ kind_of_board }}" }
    # update software
    - apt_get_upgrade
    - update_firmware
    # essential
    - setup_first
