---
# ----- Raspberry Pi first setup -----
- name: setup
  hosts: all
  pre_tasks:
    - name: remove known host keys from localhost
      shell: ssh-keygen -R {{ item | lower }} 2> /dev/null
      with_items: "{{ inventory_hostname }}"  
      delegate_to: localhost
      ignore_errors: true
      
  roles:
    - set_authorized_key
