---
- name: Setup USB-GPS Module
  hosts: Leon.local
  tasks:
    - name: apt-get install additional pkgs
      become: true
      apt:
        name: "{{ item }}"
        state: latest
        force: yes
        update_cache: yes
      with_items:
        - gpsd
        - gpsd-clients
        - python-gps

