---
- name: setup wifi
  hosts: all
  pre_tasks:
    - include_tasks: 'roles/common/get_board_kind.yml'

  roles:
    - setup_usb_wifi_adapter
    - { role: setup_wifi_ap, board: "{{ kind_of_board }}" }
