---
add_pkgs:
  # Avahi
  - avahi-daemon
  - avahi-autoipd
  - avahi-utils
  # Samba
  - samba
  - samba-common
  - samba-common-bin
  # Remote desktop
  - tightvncserver
  - xrdp
  # GPIO
  - i2c-tools
  - libi2c-dev
  - python-smbus
  - python-gpiozero
  - python3-gpiozero
  # Fonts
  - fonts-takao
  # Japanese Input Method
  - ibus-mozc
  # Web Browser
  - iceweasel
  # Tools
  - zip
  - unzip
  - exfat-fuse

samba_file: /etc/samba/smb.conf
samba_conf: |
  [share_{{ inventory_hostname[0] }}]
     path = {{ ansible_user_dir }}
     writable = yes
     guest ok = yes
     guest only = yes
     create mode = 0777
     directory mode = 0777
     share modes = yes
     force user = {{ ansible_user_id }}
samba_user: "{{ ansible_user_id }}"
samba_service_src: smb_service.txt
samba_service_dest: /etc/avahi/services/smb.service
