---
# ----- vars file for build scientific-python ----
pyenv_cmd: "{{ ansible_user_dir }}/.pyenv/bin/pyenv"

build_sp:
  setup_paths:
    - "{{ ansible_user_dir }}/.pyenv/plugins/pyenv-virtualenv/shims"
    - "{{ ansible_user_dir }}/.pyenv/shims"
    - "{{ ansible_user_dir }}/.pyenv/bin"
    - "/usr/local/sbin"
    - "/usr/local/bin"
    - "/usr/sbin"
    - "/usr/bin"
    - "/sbin"
    - "/bin"
  based_python: 3.6.5
  virtual_python: scientific
  virtual_setup_dir: "{{ ansible_user_dir }}/scientific"
  # --- list & dict---
  add_pkgs:
    - build-essential
    - libatlas-base-dev
    - libatlas-doc
    - liblapack-dev
    - libopenblas-base
    - libopenblas-dev
    - gfortran
    - libtiff5-dev
    - libhdf5-serial-dev
    - python-pip
    - python3-pip      
    - python-dev
    - python3-dev
    - python-setuptools
    - python3-setuptools
    # --- Optional ---
    - python-numpy
    - python3-numpy
    - python-matplotlib
    - python3-matplotlib
    - python-scipy
    - python3-scipy
  pip_science_pkgs:
    # --- Package Managements ---
    - pip
    - setuptools
    - wheel
    - python-debian
    # --- Fundamental Packages ---
    - six
    - urllib3
    - cython
    # --- Tool Packages ---
    - nose              # for UnitTest
    - pipdeptree        # for checking the package dependencies
    # --- GPIO Control Packages ---
    - wiringpi          # for Raspberry Pi GPIO
    - pyserial          # General Serial Port Control
    - RPi.GPIO          # for Raspberry Pi GPIO
    - picamera          # for Raspberry Pi Camera
    - pifacecommon      # for PiFace products.
    - pifacedigitalio   # for PiFace Digital I/O
    # --- Scientific Packages ---
    - numpy
    - numexpr
    - scipy
    - bottleneck
    - py-cpuinfo
    - tables
    - sympy
    - simpy
    - pandas
    - openopt
    - param
    # --- Image Proccessing ---
    - pillow
    # --- Interactive Environments ---
    - ipython
    - jupyter
    - notebook
    - jupyterlab
    # - jupyter_contrib_nbextensions
    - ipyparallel
    - bash_kernel
    # --- Graphical Package --
    - matplotlib
    - bokeh
    - plotly
    - seaborn
    - vispy
    - 'holoviews[recommended]'
    # --- Machine Learning ---
    - scikit-learn
