---
# ----- enable i2c module -----
#
#- name: check i2c module
#  shell: i2cdetect -y 1
#  register: i2c_result
#  changed_when: "'Error' in i2c_result.stderr"
#  ignore_errors: yes

- block:
  - name: include vars
    include_vars: "{{ enable_i2c_state }}.yml"
  - name: add i2c module name in /etc/modules
    become: yes
    lineinfile: >
      dest={{ etc_modules_file }}
      line={{ item }}
      state={{ etc_modules_state }}
    with_items: "{{ etc_modules_items }}"
    register: modules
  - name: add i2c module name in /boot/config.txt
    become: yes
    replace: >
      dest={{ boot_config_file }}
      replace={{ item.replace }}
      regexp={{ item.regexp }}
    with_items: "{{ boot_config_items }}"
    register: config
  - name: reboot machine
    include: roles/common/reboot.yml
    when: (modules|changed) or (config|changed)

