---
# ----- get board infomation -----
# 
# 12 Apr. 2018

- block:
  - name: check kind of board
    shell: |
      KEY=Details: &&  gpio -v | grep $KEY | sed -e "s/$KEY//g" -e 's/ *$//g'
    args:
      executable: /bin/bash
    register: board
    ignore_errors: true
    changed_when: board.stderr != ""
        
  - name: set_fact kind_of_board
    set_fact: 
      kind_of_board: "{{ board.stdout | replace(' ','_') | lower }}"
      
  - debug: var=kind_of_board

