---
# ----- reboot machine -----
#
# Refer to
# https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
# 
# 28 Feb. 2017

- name: restart machine
  become: yes
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: yes

- name: wait for SSH port down
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped
  ignore_errors: yes

- name: wait for SSH port up
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=30
