---
install_mjpg_streamer:
  add_pkgs:
    - subversion
    - libjpeg-dev
    - imagemagick
    - cmake
    - libv4l-dev
  repo: 'https://github.com/jacksonliam/mjpg-streamer.git'
  dest: '/usr/local/src/mjpg-streamer'   
  build_dir: '/usr/local/src/mjpg-streamer/mjpg-streamer-experimental'
  build_items:
    - make USE_LIBV4L2=true clean all
    - make install
