---
# Setup MJPG-streamer
#   - refer to http://ogane.com/homebrew/rpi/1522/index.html

- name: apt-get install additional pkgs
  become: true
  apt:
    name: "{{ install_mjpg_streamer.add_pkgs }}"
    state: latest
    force: yes
    update_cache: yes

- name: download source code of mjpg-streamer
  become: true
  git:
    repo: "{{ install_mjpg_streamer.repo }}"
    dest: "{{ install_mjpg_streamer.dest }}"
    update: true
  register: mjpg_streamer

- name: build mjpg-streamer
  become: true
  shell: "{{ item }}"
  args:
    chdir: "{{ install_mjpg_streamer.build_dir}}"
  with_items: "{{ install_mjpg_streamer.build_items }}"
  when: mjpg_streamer|changed
