---
# ----- firmware update -----

- name: firmware update
  become: yes
  shell: rpi-update
  register: result
  changed_when: "'firmware is already up to date' not in result.stdout"
  notify:
    - reboot

#- name: reboot machine
#  include: roles/common/reboot.yml
#  when: result|changed
