---
# ----- firmware update -----

- name: firmware update
  become: yes
  shell: rpi-update <<< 'y\n'
  ignore_errors: yes
  register: result
  changed_when: "'reboot is needed' in result.stdout"

- name: reboot machine
  include: roles/common/reboot.yml
  when: result|changed
