---
# ----- firmware update -----

- name: firmware update
  become: true
  shell: rpi-update <<< 'y\n'
  args:
    executable: '/bin/bash'
  ignore_errors: true
  register: result
  when: kind_of_board == 'raspberry_pi'
  changed_when: "'reboot is needed' in result.stdout"
  notify:
    - reboot

#- name: reboot machine
#  import_tasks: 'roles/common/reboot.yml'
#  when: result|changed
