---
# ----- firmware update -----

- name: firmware update
  become: true
  shell: rpi-update <<< 'y\n'
  args:
    executable: '/bin/bash'
  ignore_errors: true
  register: result
  changed_when: "'reboot is needed' in result.stdout"

- name: reboot machine
  include: 'roles/common/reboot.yml'
  when: result|changed
