---
# ----- vars file for install fdk-aac & ffmpeg ----
install_ffmpeg:
  working_dir: '/usr/local/src'
  fdk_aac_source: 'https://github.com/mstorsjo/fdk-aac/tarball/master'
  ffmpeg_source:  'https://www.ffmpeg.org/releases/ffmpeg-3.1.1.tar.xz'
  myconfig: myconfig.sh
  add_pkgs:
    - autoconf
    - automake
    - build-essential
    - libass-dev
    - libfreetype6-dev
    - libsdl1.2-dev
    - libtheora-dev
    - libtool
    - libva-dev
    - libvdpau-dev
    - libvorbis-dev
    - libxcb1-dev
    - libxcb-shm0-dev
    - libxcb-xfixes0-dev
    - pkg-config
    - texinfo
    - zlib1g-dev
    - yasm
    - libx264-dev
  build_fdkaac_items:
    armv6l:
      - autoreconf -fiv
      - ./configure
      - make
      - sudo make install  
    armv7l: # use 4-cores in cpu
      - autoreconf -fiv
      - ./configure
      - make -j4
      - sudo make install
  build_ffmpeg_items:
    armv6l:
      - sh myconfig.sh
      - time make 2>&1 | tee make.log
      - sudo make install
      - sudo /sbin/ldconfig
    armv7l: # use 4-cores in cpu
      - sh myconfig.sh
      - time make -j4 2>&1 | tee make.log
      - sudo make install
      - sudo /sbin/ldconfig
