---

# ----- set timezone -----
- block:
    - name: create timezone file
      become: true
      copy:
        src:  "{{ timezone.src }}"
        dest: "{{ timezone.dest }}"
        mode: 0644
    - name: update timezone
      become: true
      shell: dpkg-reconfigure --frontend noninteractive tzdata
      changed_when: false
  tags:
    - set_timezone

# ----- set keyboard layout -----
- block:
    - name: create keyboard keymap file
      become: true
      copy:
        src:  "{{ keyboard.src }}"
        dest: "{{ keyboard.dest }}"
        mode: 0644
    - name: update keymap
      become: true
      shell: /etc/init.d/keyboard-setup.sh reload
      changed_when: false
  tags:
    - set_keyboard

# ----- set locale -----
- block:
    - name: enable locales
      become: true
      replace:
        dest: '{{ locale.file }}'
        replace: '{{ item }}'
        regexp: '^#?\s*{{ item }}'
      with_items: "{{ locale.langs.enable }}"
      
    - name: disable locales
      become: true
      replace:
        dest: '{{ locale.file }}'
        replace: '# {{ item }}'
        regexp: '^{{ item }}'
      with_items: "{{ locale.langs.disable }}"
      
    - name: update locale
      become: true
      shell: locale-gen
      changed_when: false
      
    - name: set default locale
      become: true
      shell: update-locale LANG={{ locale.default_lang }}
      changed_when: false
  tags:
    - set_locale

# ----- set Wi-Fi country -----
# shell: raspi-config nonint do_wifi_country {{ wifi.country }}
- name: set wifi country
  become: true
  lineinfile:
    dest:   "{{ wifi.dest }}"
    line:   country={{ wifi.country }}
    regexp: "^country="
    state:  present
  notify:
    - restart wpa_supplicant
  tags:
    - set_wifi_country

    
      