---
# ----- install pyenv -----
# install additional pkgs
- name: apt-get install packages for pyenv
  become : true
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
    update_cache: yes
  with_items: "{{ install_pyenv.add_pkgs }}"

# install pyenv & pyenv-vitrualenv
- name: git clone pyenv
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    update: yes
  with_items: "{{ install_pyenv.git }}"
  
- name: add pyenv path in .bashrc       
  lineinfile:
    path: "{{ install_pyenv.add_bashrc.path }}"
    line: "{{ item }}"
  register: bashrc_changed
  with_items: "{{ install_pyenv.add_bashrc.line }}"

- name: source bashrc
  shell: bash -lc "source {{ install_pyenv.add_bashrc.path }}"
  when: bashrc_changed|changed
  
# install new pythons
- name: check python versions in virtual environment
  shell: pyenv versions
  register: installed_python_envs
  changed_when: false
  ignore_errors: yes
  
# - debug: var=installed_python_envs.stdout_lines

- name: install python
  shell: pyenv install {{ item }} -f
  when: item not in installed_python_envs.stdout
  with_items: "{{ install_pyenv.python_versions }}"

- name: pyenv rehash
  shell: pyenv rehash
  changed_when: false
