---
# ----- i2c module -----
i2c_module:
  enabled:
    module_items:
      - { line: 'i2c-bcm2708', state: present }
      - { line: 'i2c-dev',     state: present }
    config_items:
      - regexp:  '^#?\s*dtparam=i2c_arm=on'
        replace: 'dtparam=i2c_arm=on'
  disabled:
    module_items:
      - { line: 'i2c-bcm2708', state: absent  }
      - { line: 'i2c-dev',     state: present }
    config_items:
      - regexp:  '^dtparam=i2c_arm=on'
        replace: '#dtparam=i2c_arm=on'
  unchanged:
    module_items:
      - { line: None, state: absent }
    config_items:
      - regexp:  None
        replace: None

