---
- name: Ansible Command Test
  hosts: localhost
  tasks:
  - name: pyenv
    stat: path=/usr/local/bin/pyenv
    register: result
    changed_when: not result.stat.exists

  - name: Install pyenv
    debug: msg="pyenv is not installed"
    when: result is changed

  - name: Install pyenv
    debug: msg="pyenv is installed"
    when: result is not changed
