---
- name: iMac's tasks
  hosts: localhost
  user: takamasa
  gather_facts: no
  tasks:
  - name: Delete local zetazero*.tsv files in the iMac
#   file: path={{item}} state=absent  
    shell: mv {{ item }} {{ item | dirname }}/.Trash/{{ item | basename }}
    with_fileglob:
      - ~/zetazero*.tsv

- name: Every Raspberry Pi's tasks
  hosts: zetazero
  tasks:
  - name: Get zetazero*.tsv files from Raspberry Pis
    script: move-data.sh -m
    args:
      executable: /bin/bash
      chdir: "{{ ansible_user_dir }}/ZetaZero"
