---
timezone:
  { src: timezone.txt , dest: /etc/timezone }

keyboard:
  { src: keyboard.txt , dest: /etc/default/keyboard }
  
locale_file: /etc/locale.gen
locales:
  - { lang: 'en_GB.UTF-8 UTF-8',   enable: False }
  - { lang: 'en_US.UTF-8 UTF-8',   enable: True }
  - { lang: 'ja_JP.EUC-JP EUC-JP', enable: True }
  - { lang: 'ja_JP.UTF-8 UTF-8',   enable: True }
default_locale: en_US.UTF-8

wifi:
  { dest: /etc/wpa_supplicant/wpa_supplicant.conf , country: JP}