---
timezone:
  { src: 'timezone.txt' , dest: '/etc/timezone' }

keyboard:
  { src: 'keyboard.txt' , dest: '/etc/default/keyboard' }
  
locale:
  file: '/etc/locale.gen'
  langs:
    enable:
      - 'en_US.UTF-8 UTF-8'
      - 'ja_JP.EUC-JP EUC-JP'
      - 'ja_JP.UTF-8 UTF-8'
    disable:
      - 'en_GB.UTF-8 UTF-8'
  default_lang: en_US.UTF-8

wifi:
  { dest: '/etc/wpa_supplicant/wpa_supplicant.conf' , country: 'JP' }