---
- name: edit /etc/modules
  become: true
  lineinfile:
    dest:  "{{ dest.modules }}"
    line:  "{{ item.line }}"
    state: "{{ item.state }}"
  with_flattened:
    - "{{ i2c_module[  i2cQ  | default('unchanged')].module_items }}"
    - "{{ v4l2_module[ v4l2Q | default('unchanged')].module_items }}"
  when: item.line != None
  register: modules_state

- name: edit /boot/config.txt
  become: true
  replace:
    dest:    "{{ dest.config }}"
    replace: "{{ item.replace }}"
    regexp:  "{{ item.regexp }}"
  when: item.replace != None
  with_flattened:
    - "{{ i2c_module[      i2cQ      | default('unchanged')].config_items }}"
    - "{{ picamera_module[ picameraQ | default('unchanged')].config_items }}"
  register: config_state

- name: reboot machine
  include: 'roles/common/reboot.yml'
  when: (modules_state|changed) or (config_state|changed)
