---
- include_vars: "i2c_{{ enable_i2c_state }}.yml"
- include_vars: "v4l2_{{ enable_v4l2_state }}.yml"
- include_vars: "picamera_{{ enable_picamera_state }}.yml"    

- name: edit /etc/modules
  become: yes
  lineinfile: >
    dest={{ etc_modules_file }}
    line={{ item.line }}
    state={{ item.state }}
  with_flattened:
    - "{{ i2c_modules_items }}"
    - "{{ v4l2_modules_items }}"
  register: modules

- name: edit /boot/config.txt
  become: yes
  replace: >
    dest={{ boot_config_file }}
    replace={{ item.replace }}
    regexp={{ item.regexp }}
  with_flattened:
    - "{{ i2c_config_items }}"
    - "{{ picamera_config_items }}"
  register: config

- name: reboot machine
  include: roles/common/reboot.yml
  when: (modules|changed) or (config|changed)
