---
# ----- install additional packages for OWFS -----
- name: apt-get install packages for OWFS
  apt: name={{ item }} state=latest force=yes
  with_items: "{{ install_owfs.add_pkgs }}"

# ----- download the latest version of OWFS -----
- name: download OWFS file
  get_url:
    url:  "{{ install_owfs.url }}"
    dest: "{{ install_owfs.src_dir }}"
  register: owfs_tar

- name: unarchive OWFS file
  unarchive:
    src:  "{{ owfs_tar.dest }}"
    dest: "{{ install_owfs.src_dir }}"
    copy: false
    list_files: true
  register: archived

- name: check OWFS config.log
  stat: path={{ install_owfs.src_dir }}/{{ archived.files[0] }}/config.log
  register: owfs_is_maked

# ----- install OWFS -----
- block:
  - name: install OWFS
    become: true
    shell: "{{ item }}"
    args:
      chdir: "{{ install_owfs.src_dir }}/{{ archived.files[0] }}"
    with_items: "{{ install_owfs.build_items[ ansible_architecture ] }}"
  when: not owfs_is_maked.stat.exists

- name: make OWFS mount directory
  file:
    path:  "{{ install_owfs.mnt_dir}}"
    state: directory

- name: edit /etc/fuse.conf
  lineinfile:
    dest: '/etc/fuse.conf'
    line: 'user_allow_other'
    regexp: '^#?\s*user_allow_other'

- name: copy start1wire.sh
  copy:
    src:  "{{ install_owfs.service_file }}"
    dest: '/etc/init.d'
    mode: "u=rwx,g=rx,o=rx"
  register: owfs_service
  
- block:
  - name: regist start1wire service
    shell: update-rc.d {{ install_owfs_service_file }} defaults
    args:
      chdir: '/etc/init.d'
    changed_when: false
    
  - name: reboot machine
    include: 'roles/common/reboot.yml'
  when: owfs_service|changed
