---
# ----- install additional packages for OWFS -----
- name: apt-get install packages for OWFS
  apt: name={{ item }} state=latest force=yes
  with_items: '{{ install_owfs_add_pkgs }}'

# ----- download the latest version of OWFS -----
- name: download OWFS file
  get_url: >
    url={{ install_owfs_url }}
    dest={{ install_owfs_src_dir }}
  register: owfs_tar

- name: unarchive OWFS file
  unarchive: >
    src={{ owfs_tar.dest }}
    dest={{ install_owfs_src_dir }}
    copy=no
    list_files=yes
  register: owfs

- name: check OWFS config.log
  stat: path={{ install_owfs_src_dir }}/{{ owfs.files[0] }}/config.log
  register: owfs_is_maked

- block:
  - include_vars: armv6l.yml
    when: ansible_architecture == 'armv6l'
  - name: install OWFS
    become: yes
    shell: "{{ item }}"
    args:
      chdir: "{{ install_owfs_src_dir }}/{{ owfs.files[0] }}"
    with_items: "{{ install_owfs_build_items }}"
  when: not owfs_is_maked.stat.exists

- name: make OWFS mount directory
  file: >
    path={{ install_owfs_mnt_dir}}
    state=directory

- name: edit /etc/fuse.conf
  lineinfile: >
    dest=/etc/fuse.conf
    line=user_allow_other
    regexp='^#?\s*user_allow_other'

- name: copy start1wire.sh
  copy: >
    src={{ install_owfs_service_file }}
    dest=/etc/init.d
    mode="u=rwx,g=rx,o=rx"
  register: owfs_service
  
- block:
  - name: regist start1wire service
    shell: update-rc.d {{ install_owfs_service_file }} defaults
    args:
      chdir: /etc/init.d
    register: owfs
    changed_when: no
  - name: reboot machine
    include: '{{ reboot }}'
  when: owfs_service|changed
