---
# ----- install ffmpeg with fdk-aac-----
# refer to http://d.hatena.ne.jp/embedded/20151011/p2

- name: apt-get install add pkgs
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
    update_cache: yes
  with_items: "{{ install_ffmpeg.add_pkgs }}"

# --- install fdk-aac ---
- name: wget fdk-aac
  become: true
  get_url:
    url: "{{ install_ffmpeg.fdk_aac_source }}"
    dest: "{{ install_ffmpeg.working_dir }}"
  register: fdkacc_tar

- name: unarchive fdk-aac
  become: true
  unarchive:
    src: "{{ fdkacc_tar.dest }}"
    dest: "{{ install_ffmpeg.working_dir }}"
    copy: false
    list_files: true
  register: fdk_acc

- name: build fdk-acc
  become: true
  shell: "{{ item }}"
  args:
    chdir: "{{ install_ffmpeg.working_dir }}/{{ fdk_acc.files[0] }}"
  with_items: "{{ install_ffmpeg.build_fdkaac_items[ ansible_architecture ] }}"
  changed_when: false
  when: fdkacc_tar|changed

# --- install ffmpeg ---
- name: wget ffmpeg
  become: true
  get_url:
    url: "{{ install_ffmpeg.ffmpeg_source }}"
    dest: "{{ install_ffmpeg.working_dir }}"
  register: ffmpeg_tar

- name: unarchive ffmpeg
  become: true
  unarchive:
    src: "{{ ffmpeg_tar.dest }}"
    dest: "{{ install_ffmpeg.working_dir }}"
    copy: false
    list_files: true
  register: ffmpeg

- name: copy myconfig.sh
  become: true
  copy:
    src: "{{ install_ffmpeg.myconfig }}"
    dest: "{{ install_ffmpeg.working_dir }}/{{ ffmpeg.files[0] }}"
      
- name: build ffmpeg
  become: true
  shell: "{{ item }}"
  args:
    chdir: "{{ install_ffmpeg.working_dir }}/{{ ffmpeg.files[0] }}"
  with_items: "{{ install_ffmpeg.build_ffmpeg_items[ ansible_architecture ] }}"
  changed_when: false
  when: ffmpeg_tar|changed
