---
# ----- install ffmpeg with fdk-aac-----
# refer to http://d.hatena.ne.jp/embedded/20151011/p2

- name: apt-get install add pkgs
  become: true
  apt: name={{ item }} state=latest force=yes
  with_items: "{{ install_ffmpeg_add_pkgs }}"

# --- check architecture ---
- include_vars: armv6l.yml
  when: ansible_architecture == 'armv6l'

# --- install fdk-aac ---
- name: wget fdk-aac
  become: true
  get_url:
    url:  "{{ install_ffmpeg_fdk_aac_source }}"
    dest: "{{ install_ffmpeg_working_dir }}"
  register: fdkacc_tar

- name: unarchive fdk-aac
  become: true
  unarchive:
    src:  "{{ fdkacc_tar.dest }}"
    dest: "{{ install_ffmpeg_working_dir }}"
    copy: false
    list_files: true
  register: fdkacc

- name: build fdk-acc
  become: true
  shell: "{{ item }}"
  args:
    chdir: "{{ install_ffmpeg_working_dir }}/{{ fdkacc.files[0] }}"
  with_items: "{{ install_ffmpeg_build_fdkaac_items }}"
  changed_when: false
  when: fdkacc_tar|changed

# --- install ffmpeg ---
- name: wget ffmpeg
  become: true
  get_url:
    url:  "{{ install_ffmpeg_ffmpeg_source }}"
    dest: "{{ install_ffmpeg_working_dir }}"
  register: ffmpeg_tar

- name: unarchive ffmpeg
  become: true
  unarchive:
    src:  "{{ ffmpeg_tar.dest }}"
    dest: "{{ install_ffmpeg_working_dir }}"
    copy: false
    list_files: true
  register: ffmpeg

- name: copy myconfig.sh
  become: true
  copy:
    src:  "{{ install_ffmpeg_myconfig }}"
    dest: "{{ install_ffmpeg_working_dir }}/{{ ffmpeg.files[0] }}"
      
- name: build ffmpeg
  become: true
  shell: "{{ item }}"
  args:
    chdir: "{{ install_ffmpeg_working_dir }}/{{ ffmpeg.files[0] }}"
  with_items: "{{ install_ffmpeg_build_ffmpeg_items }}"
  changed_when: false
  when: ffmpeg_tar|changed
