---
# ----- install motion -----
# refer to http://qiita.com/rukihena/items/95da3860f9ca86c39f8d

# install motion
- name: apt-get install motion
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
    update_cache: yes
  with_items:
    - motion

- name: set permission
  become: true
  file:
    path: "{{ install_motion.lib_oath }}"
    state: directory
    group: "{{ install_motion.user }}"

# setup config
- name: mkdir .motion
  file:
    path: "{{ install_motion.dest_path }}"
    state: directory
    force: true

- name: set motion.conf
  copy:
    src: "{{ install_motion.config_file }}"
    dest: "{{ install_motion.dest_path }}"
