---
- name: restart avahi-daemon
  become: true
  systemd:
    name: avahi-daemon
    state: restarted

- name: restart samba
  become: true
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - smbd
    - nmbd
