---
# ----- set bash aliases -----
- name: copy .bash_aliases
  copy:
    src: 'bash_aliases'
    dest: "{{ ansible_user_dir }}/.bash_aliases"
    force: no
  tags:
    - set bash aliases

# ----- add pkgs -----
- name: apt-get install additional pkgs
  become: true
  apt: name={{ item }} state=latest force=yes
  with_items: "{{ add_pkgs }}"
  ignore_errors: yes
  notify:
    - restart avahi-daemon
  tags:
    - add software

# --- setup avahi ---
- name: copy service file
  become: true
  copy:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ avahi_service }}"
  notify:
    - restart avahi-daemon
  tags:
    - avahi service

# --- setup samba ---
- block:
  - name: edit smb.conf
    become: true
    blockinfile:
      dest: "{{ samba_file }}"
      block: "{{ samba_conf }}"
    notify:
     - restart samba
      
  - name: add samba user
    become: true
    shell: |
      (echo {{ samba_pwd }}; echo {{ samba_pwd }}) | smbpasswd -s -a {{ samba_user }}
    args:
      executable: '/bin/bash'
    changed_when: false
  tags:
    - setup samba
