---
- name: apt-get upgrade
  become : true
  apt:
    upgrade: full
    force: yes
    update_cache: yes
  ignore_errors: yes

- name: apt-get dist-upgrade
  become : true
  apt:
    upgrade: dist
    force: yes
  ignore_errors: yes
