---
# ----- vars file for install pyenv ----
install_pyenv:
# --- add package for installing pyenv ---
  add_pkgs:
    - build-essential
    - libncursesw5-dev
    - libgdbm-dev
    - libc6-dev
    - zlib1g-dev
    - libsqlite3-dev
    - tk-dev
    - libssl-dev
    - openssl
    - libbz2-dev
    - libreadline-dev
    - libffi-dev

# --- for pyenv & pyenv-virtualenv ---
  git:
    - repo: 'https://github.com/yyuu/pyenv.git'
      dest: '~/.pyenv'
    - repo: 'https://github.com/yyuu/pyenv-virtualenv.git'
      dest: '~/.pyenv/plugins/pyenv-virtualenv'
    - repo: 'https://github.com/yyuu/pyenv-virtualenvwrapper.git'
      dest: '~/.pyenv/plugins/pyenv-virtualenvwrapper'

  add_bashrc:
    path: "{{ ansible_user_dir }}/.bashrc"
    line:
      - export PYENV_ROOT="$HOME/.pyenv"
      - export PATH="$PYENV_ROOT/bin:$PATH"
      - eval "$(pyenv init -)"
      - eval "$(pyenv virtualenv-init -)"

# --- installing python version on pyenv ---
  python_versions:
    - 2.7.15
    - 3.7.1
