---
# ----- vars file for install pyenv ----
# --- add package for installing pyenv ---
install_pyenv_add_pkgs:
  - build-essential
  - libncursesw5-dev
  - libgdbm-dev
  - libc6-dev
  - zlib1g-dev
  - libsqlite3-dev
  - tk-dev
  - libssl-dev
  - openssl
  - libbz2-dev
  - libreadline-dev

# --- for pyenv & pyenv-virtualenv ---
install_pyenv_git: 
  - repo: 'https://github.com/yyuu/pyenv.git'
    dest: '~/.pyenv'
  - repo: 'https://github.com/yyuu/pyenv-virtualenv.git'
    dest: '~/.pyenv/plugins/pyenv-virtualenv'

install_pyenv_add_profile:
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - eval "$(pyenv virtualenv-init -)"

# --- installing python version on pyenv ---
install_pyenv_python_versions:
  - 2.7.13
  - 3.6.2
